login/app.py
def create_app_login():
    from flask import Flask, render_template, redirect, url_for, request, session
    from pymongo import MongoClient

    app = Flask(__name__)

    URI_config = "mongodb://localhost:27017"
    nome_config = "Site_Flask"
    collection_name_config = "BD_LOGIN"

    app.secret_key = b'_5#y2L"F4Q8z\n\xec]/'

    client = MongoClient(URI_config)
    db = client[nome_config]
    collection = db[collection_name_config]

    @app.route('/')
    def index():
        login = request.args.get('username', '')
        senha = request.args.get('password', '')
        user_data = collection.find_one({'username': login, 'password': senha})
        if user_data:
            print('Login bem sucedido')
            return redirect(url_for('login'))
        return render_template('index.html')

        

    @app.route('/login', methods=['GET', 'POST'])
    def login():
        if request.method == 'POST':
            username = request.form['username']
            password = request.form['password']
            
            user_data = collection.find_one({'username': username, 'password': password})
            if user_data:
                session['username'] = username
                return redirect('http://127.0.0.1:8080/')
            else:
                return render_template('login.html', error='Credenciais inválidas. Tente novamente.')
        
        return render_template('login.html')


    @app.route('/register', methods=['GET', 'POST'])
    def register():
        if request.method == 'POST':
            username = request.form['username']
            password = request.form['password']
            if collection.find_one({'username': username}):
                return render_template('register.html', error='Nome de usuário já existe. Tente outro.')
            else:
                collection.insert_one({'username': username, 'password': password})
                return redirect(url_for('index')) 
        return render_template('register.html')


    @app.route('/logout')
    def logout():
        session.pop('username', None)
        return redirect(url_for('index'))

    @app.route('/forgot-password')
    def forgot_password():
        return render_template('forgot.html')
    
    return app

main.py
def create_app():
    from flask import Flask, render_template
    from routes.home import home_route
    from routes.cliente import cliente_route
    
    app = Flask(__name__)

    app.register_blueprint(home_route)
    app.register_blueprint(cliente_route, url_prefix="/clientes")

    return app

routes/cliente.py
from flask import Blueprint, render_template, request
from database.cliente import CLIENTES


cliente_route = Blueprint('cliente', __name__)

'''
Rota de Clientes

/clientes/ (GET) – Listar os clientes
/clientes/ (POST) – inserir o cliente no servidor
/clientes/new (GET) – renderizar o formulário para criar um cliente
/clientes/<id> (GET) – obter os dados de um cliente
/clientes/<id>/edit (GET) – renderizar um formulário para editar um cliente
/clientes/<id>/update (PUT) – atualizar os dados do cliente
/clientes/<id>/delete (DELETE) – deleta o registro do usuário
'''

@cliente_route.route('/')
def lista_clientes():
    return render_template('lista_clientes.html', clientes=CLIENTES)

@cliente_route.route('/', methods=['POST'])
def inserir_cliente():
    data = request.json
    
    novo_usuario = {
        "id": len(CLIENTES) + 1,
        "nome": data['nome'],
        "email": data['email'],
    }
    CLIENTES.append(novo_usuario)
    
    return render_template('item_cliente.html', cliente=novo_usuario)



@cliente_route.route('/new')
def form_cliente():
    return render_template('form_cliente.html')

@cliente_route.route('/<int:cliente_id>')
def detalhe_cliente(cliente_id):
    
    cliente = list(filter (lambda c: c['id'] == cliente_id, CLIENTES))[0]
    return render_template('detalhe_cliente.html', cliente=cliente)


@cliente_route.route('/<int:cliente_id>/edit')
def form_edit_cliente(cliente_id):
    cliente = None
    for c in CLIENTES:
        if c['id'] == cliente_id:
            cliente = c
    
    return render_template('form_cliente.html', cliente = cliente)

@cliente_route.route('/<int:cliente_id>/update', methods=['PUT'])
def atualizar_cliente(cliente_id):
    cliente = None
    data = request.json
    for c in CLIENTES:
        if c['id'] == cliente_id:
            c['nome'] = data['nome']
            c['email'] = data['email']
            cliente = c    
    
    return render_template('item_cliente.html', cliente=cliente)


@cliente_route.route('/<int:cliente_id>/delete', methods=['DELETE'])
def deletar_cliente(cliente_id):
    global CLIENTES
    CLIENTES = [ c for c in CLIENTES if c['id'] != cliente_id]
    return {'delete': 'ok'}

routes/home.py
from flask import Blueprint, render_template

home_route = Blueprint('home', __name__)

@home_route.route('/')
def index():
    return render_template('index.html')

templates/detalhe_cliente.html
<ul>
    <li>ID: {{cliente.id}}</li>
    <li>Nome: {{cliente.nome}}</li>
    <li>E-mail: {{cliente.email}}</li>
</ul>

templates/form_cliente.html
<form class="c-form" 
        {% if cliente %}
            action="{{ url_for('cliente.atualizar_cliente', cliente_id = cliente.id) }}" 
        {% else %}
            action="{{ url_for('cliente.inserir_cliente') }}" 
        {% endif %}

        {% if cliente %}
        method="PUT"
        {% else %} 
        method="POST"
        {% endif %}   

        {% if cliente %}
            c-swap=".cliente-{{cliente.id}}"
        {% else %}
            c-append="#lista-clientes">
        {% endif %}


    <div class="mb-3">
        <label for="nome" class="form-label">Nome</label>
        <input type="text" class="form-control" id="nome" name="nome" {% if cliente %} value="{{ cliente.nome }}" {% endif %}>

    </div>
  
    <div class="mb-3">
        <label id="label-target" for="email" class="form-label">Email</label>
        <input type="text" class="form-control" id="email" name="email" {% if cliente %} value="{{ cliente.email }}" {% endif %}>
    </div>
  
    <button type="submit" class="btn btn-primary"> {% if cliente %} Salvar {% else %} Criar {% endif %} </button>
</form>

templates/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Gestão de Clientes</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/app.css') }}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap">

</head>
<body>


<div class="container">

    <h1>Gestão de Clientes</h1>

    <!-- Formulario ADD Cliente -->
    <div id="form-cliente" c-container="{{ url_for('cliente.form_cliente') }}"></div> 

    <hr>

    <h2>Lista de Clientes</h2>
    <!-- Lista de clientes  -->
    <div id="lista-clientes" c-container="{{ url_for('cliente.lista_clientes') }}"></div>

</div>


  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Informações</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body" id="exibir-cliente">
          ...
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
        </div>
      </div>
    </div>
  </div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<script src="{{ url_for('static', filename='js/cru.js') }}"></script>
</body>
</html>

templates/item_cliente.html
<tr class="cliente-{{cliente.id}}">
    <th scope="row">{{ cliente.id }}</th>
    <td>{{ cliente.nome }}</td>
    <td>{{ cliente.email }}</td>
    <td>
        <button class="btn btn-secondary" c-get="{{ url_for('cliente.detalhe_cliente', cliente_id = cliente.id) }}" c-target="#exibir-cliente" data-bs-toggle="modal" data-bs-target="#exampleModal">Ver</button>
        <button class="btn btn-primary" c-get="{{ url_for('cliente.form_edit_cliente', cliente_id = cliente.id) }}" c-target="#form-cliente">Editar</button>
        <button class="btn btn-danger" c-delete="{{ url_for('cliente.deletar_cliente', cliente_id=cliente.id) }}" c-remove-closest="tr" >Deletar</button>
    </td>
</tr>

templates/lista_clientes.html
<table class="table">
  <thead>
      <tr>
          <th scope="col">#</th>
          <th scope="col">Nome</th>
          <th scope="col">Email</th>
          <th scope="col">Ações</th>
      </tr>
  </thead>
  <tbody id="lista-clientes">
      {% for cliente in clientes %}
        {% include 'item_cliente.html' %}
      {% endfor %}
  </tbody>
</table>